# Generated by Django 4.0.3 on 2022-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_yeguliklar_nomi_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeguliklar',
            name='narx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
