# Generated by Django 4.0.3 on 2022-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_aloqa_xabar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stol_Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('vaqt', models.DateTimeField()),
                ('soni', models.IntegerField(blank=True, null=True)),
                ('izoh', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
