# Generated by Django 4.0.3 on 2022-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_stol_buyurtma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stol_buyurtma',
            name='vaqt',
            field=models.DateField(),
        ),
    ]
