# Generated by Django 4.0.3 on 2022-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_stol_buyurtma_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stol_buyurtma',
            name='sana',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stol_buyurtma',
            name='vaqt',
            field=models.TimeField(null=True),
        ),
    ]
